### PR TITLE
add third geo

### PR DESCRIPTION
**Pull request by JuanCaicedo**
@sandinmyjoints 

Adds a third geo to target Canada, Australia and the UK.

### CODE REVIEW

**Comment by danpaz** [comment]
:maple_leaf:

**Comment by sandinmyjoints** [comment]
LGTM. But what's a good way to verify it worked or will work once you run it?

**Comment by JuanCaicedo** [comment]
@sandinmyjoints there isn't really, although [this](https://github.com/spanishdict/example-dfp-line-item-generator/blob/master/lib/formatter.js#L47) is the only line that uses that file. We basically just read the JSON and the select out of it.

The real test for it is running the script to create some line items in DFP for that third geo, which I've just finished doing.

**Comment by sandinmyjoints** [comment]
I see the countries here:
screen shot 2016-02-18 at 10 26 19 am

LGTM. Approved.

@danpaz Do you scan every PR for mentions of Canada? :stuck_out_tongue:

**Comment by JuanCaicedo** [comment]
+1 for the Great White North

**Comment by danpaz** [comment]
@sandinmyjoints I should write a bot to do just that. Open to suggestions for naming this bot.

**Comment by JuanCaicedo** [comment]
@danpaz `git-mountie`, `canuck-quest`, `loonie-scout`

**Comment by sandinmyjoints** [comment]
maple-scan

**Pull request merged**
